name: CI

on:
  push:
    # branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  basics:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - uses: actions/setup-node@v3
      with:
        node-version: latest

    - run: npm run lint:package
    - run: npm run lint:readme
    - run: npm run lint:editorconfig
    - run: npm run lint:man
    - run: shellcheck git-open
    - run: npm run man
    - run: ./bats/bin/bats test/*.bats
