name: CI

on:
  push:
    # branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  basics:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - uses: actions/setup-node@v3
      with:
        node-version: latest

    - run: npm run lint
    - run: npm run shellcheck
    - run: npm run unit
    - name: check if manpage needs a regen
       run: cp git-open.1 git-open.old && npm run man && git diff --no-index ./git-open.old ./git-open.1

